# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Digital_lab/lab8/Game.xdc

# IP: ip/VRAM/VRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==VRAM || ORIG_REF_NAME==VRAM} -quiet] -quiet
