# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Digital_lab/lab8/Game/Game.srcs/sources_1/ip/pclk/pclk.xci
# IP: The module: 'pclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Digital_lab/lab8/Game/Game.gen/sources_1/ip/pclk/pclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pclk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Digital_lab/lab8/Game/Game.gen/sources_1/ip/pclk/pclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Digital_lab/lab8/Game/Game.gen/sources_1/ip/pclk/pclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Digital_lab/lab8/Game/Game.srcs/sources_1/ip/pclk/pclk.xci
# IP: The module: 'pclk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Digital_lab/lab8/Game/Game.gen/sources_1/ip/pclk/pclk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Digital_lab/lab8/Game/Game.gen/sources_1/ip/pclk/pclk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Digital_lab/lab8/Game/Game.gen/sources_1/ip/pclk/pclk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pclk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
